refactoring
HeavyTechRuby/bddsm pull request #18
Opened 2024-06-12 00:40 UTC by sunnmas

2024-06-12 05:41 UTC, sergio-fry requested changes
PR does not looks like a refactoring for me, but a feature.

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/execution_statistics.rb
> +    attr_reader :successes, :failures, :errors
Why do we need errors separated from failures?

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/execution_statistics.rb
> +  class ExecutionStatistics
do we have statistics here? in terms of "Mathematical statistics"

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/expectation.rb
> +  class Expectation
In my opinion expectation should contain some expectations, but this class does not. It contains just actual value and can't be used to build expectation when expected value is passed. So Expectation should be a composite of actual, expected and matcher. But this class does not

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/expectation.rb
> +      Matcher::NotEqual.new(expected: expected)
These PR is not just a refactoring. It is a new feature here

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/describe.rb
> +    rescue It::Exception => e
Failure is not an exceptional case for me. Is it possible to avoid usage of exception as control structure here?

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/describe.rb
> +      It.new(describe: self, &block).run
It is great, that we have `It` class for now!

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm.rb
> +  def self.describe(title, &block)
actually rubocop asked me to use this syntax :)

2024-06-12 05:41 UTC, sergio-fry commented on lib/bddsm/report.rb
> +      @io.print 'E'
I don't think we should separate errors and failures in a report. Looks like it does not matter, why spec failed. Failure object should contain some details why it happed and genarate readable message.

RSpec does not make segregation in here - always "F" is used. Let's use the same notation

2024-06-12 11:51 UTC, sunnmas commented on lib/bddsm/execution_statistics.rb
> +    attr_reader :successes, :failures, :errors
Вообще не принципиально, объединю

2024-06-12 11:51 UTC, sunnmas commented on lib/bddsm/execution_statistics.rb
> +  class ExecutionStatistics
Что на счет ResultCollector?

2024-06-12 11:56 UTC, sunnmas commented on lib/bddsm/expectation.rb
> +  class Expectation
Аргумент №1 
Это примерно так же было с ввдением It.

def it
  Execution.new почему ит возвращает экзекушен возник у меня вопрос?
end
  
  
  def expect
    Actual.new здесь возник аналогичный вопрос
 end
 
Аргумент №2

class Actual
...
def to - что делает метод ту на актуальном значении? Ответ - реализует проверку ожидания
end


Может быть тогда  все таки это Ожидание?
class Expectation

def to
Чтобы придать веса, просто метод to мог бы называться по другому так:
alias :to :realize
alias :to :check
alias :to :expectation_correct?

2024-06-12 11:58 UTC, sunnmas commented on lib/bddsm/expectation.rb
> +      Matcher::NotEqual.new(expected: expected)
я ввел еще один матчер, чтобы 
1 показать что они лежат в папке матчеров
2 они оба ничего не знают о сюитэ
3 они генерят ошибку, обработка которой не входит в зону ответственности матчера

2024-06-12 12:00 UTC, sunnmas commented on lib/bddsm/describe.rb
> +    rescue It::Exception => e
хотел убрать, но я отвязал ит от дескрайба, сейчас ит ничего не знает о дескрайбе, поэтому я обрабатываю ошибку здесь и обогащаю ее информацией о названии дескрайба, чтобы вывести ее в репорт. Таким образом ит не знает о названии дескрайба

2024-06-12 12:00 UTC, sunnmas commented on lib/bddsm/describe.rb
> +      It.new(describe: self, &block).run
Это было самым сложным))))

2024-06-12 12:01 UTC, sunnmas commented on lib/bddsm.rb
> +  def self.describe(title, &block)
Я согласен, просто у меня не запускалось, разбираться не хотелось, время было позднее, верну назад

2024-06-12 12:01 UTC, sunnmas commented on lib/bddsm/report.rb
> +      @io.print 'E'
Убрал

2024-06-13 12:58 UTC, sergio-fry commented on lib/bddsm/expectation.rb
> +  class Expectation
> Это примерно так же было с ввдением It.
> 
> def it
> Execution.new почему ит возвращает экзекушен возник у меня вопрос?
> end
> 
> def expect
> Actual.new здесь возник аналогичный вопрос
> end


Это вопрос DSL: он выглядит удобным и разумным; Собственно, пока не ставилась цель переосмыслить RSpec syntax - пока копируем. Но сами классы не должны быть противоречивы внутри себя. В целом, они могут иметь проблемы сейчас. Это стоит исправлять. Я лишь указываю на противоречие в классе, что ты добавляешь. Давай будем исправлять старые ошибки и стараться не делать новых.



> Аргумент №2
> 
> class Actual
> ...
> def to - что делает метод ту на актуальном значении? Ответ - реализует проверку ожидания
> end
> 
> Может быть тогда все таки это Ожидание?
> class Expectation
> 
> def to
> Чтобы придать веса, просто метод to мог бы называться по другому так:
> alias :to :realize
> alias :to :check
> alias :to :expectation_correct?

actual.to - может формировать ожидание. Читаем так: Актуальное значение должно соответствовать matcher-у = expectation.

Опять же, actual.to -  мы тут в ограничения DSL. Если бы не он, то метод мог бы называться более точно.

2024-06-13 13:00 UTC, sergio-fry commented on lib/bddsm/expectation.rb
> +      Matcher::NotEqual.new(expected: expected)
Все верно, refactoring - это улучшение структуры кода без изменения его поведения. Твои изменения выглядят важными и нужными, давай создадим отдельный PR. Либо переформулируем данный PR, чтобы он соответствовал содержанию

2024-06-13 13:01 UTC, sergio-fry commented on lib/bddsm/describe.rb
> +    rescue It::Exception => e
Нужно подумать, как можно избежать управления через исключение

2024-06-13 14:06 UTC, sergio-fry commented on lib/bddsm/execution_statistics.rb
> +  class ExecutionStatistics
А почему тебе кажется, что собиратель результатов более точно, чем просто "результаты"?

2024-06-13 18:30 UTC, sunnmas commented on lib/bddsm/execution_statistics.rb
> +  class ExecutionStatistics
вернул result

2024-06-13 18:30 UTC, sunnmas commented on lib/bddsm/expectation.rb
> +  class Expectation
вернул actual

2024-06-13 19:33 UTC, closed without merging